sae/characters/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from sae.models import Character

class CharacterForm(FlaskForm):
    character_name = StringField("Character Name", validators=[DataRequired(), Length(min=2, max=20)])
    character_class = StringField("Class", validators=[DataRequired(), Length(min=2, max=20)])
    level = IntegerField("Level", validators=[DataRequired(), Length(min=2, max=20)])
    background = StringField("Background", validators=[DataRequired(), Length(min=2, max=20)])
    player_name = StringField("Payer Name", validators=[DataRequired(), Length(min=2, max=20)])
    race = StringField("Race", validators=[DataRequired(), Length(min=2, max=20)])
    alignment = StringField("Alignment", validators=[DataRequired(), Length(min=2, max=20)])
    exp = IntegerField("Experience Points", validators=[DataRequired(), Length(min=2, max=20)])
    strength = IntegerField("Strength", validators=[DataRequired(), Length(min=2, max=20)])
    dexterity = IntegerField("Dexterity", validators=[DataRequired(), Length(min=2, max=20)])
    constitution = IntegerField("Constitution", validators=[DataRequired(), Length(min=2, max=20)])
    wisdom = IntegerField("Wisom", validators=[DataRequired(), Length(min=2, max=20)])
    intelligence = IntegerField("Intelligence", validators=[DataRequired(), Length(min=2, max=20)])
    charisma = IntegerField("Charisma", validators=[DataRequired(), Length(min=2, max=20)])
    inspiration = BooleanField("Inspiration")
    prof = IntegerField("Proficiency Bonus", validators=[DataRequired(), Length(min=2, max=20)])
    st_str = BooleanField("Strength")
    st_dex = BooleanField("Dexterity")
    st_con = BooleanField("Constitution")
    st_wis = BooleanField("Wisdom")
    st_int = BooleanField("Intelligence")
    st_cha = BooleanField("Charisma")
    acrobatics = BooleanField("Acrobatics")
    animal_handling = BooleanField("Animal Handling")
    arcana = BooleanField("Arcana")
    athletics = BooleanField("Athletics")
    deception = BooleanField("Deception")
    history = BooleanField("History")
    insight = BooleanField("Insight")
    intimidation = BooleanField("Intimidation")
    investigation = BooleanField("Investigation")
    medicine = BooleanField("Medicine")
    nature = BooleanField("Nature")
    perception = BooleanField("Perception")
    performance = BooleanField("Performance")
    persuation = BooleanField("Persuasion")
    religion = BooleanField("Religion")
    sleight_of_hand = BooleanField("Sleight of Hand")
    stealth = BooleanField("Stealth")
    survival = BooleanField("Survival")
    armor_class = IntegerField("Armor Class", validators=[DataRequired(), Length(min=2, max=20)])
    initiative = IntegerField("Initiative", validators=[DataRequired(), Length(min=2, max=20)])
    speed = IntegerField("Speed", validators=[DataRequired(), Length(min=2, max=20)])
    hp_max = IntegerField("Hit Point Maximum", validators=[DataRequired(), Length(min=2, max=20)])
    hp_current = IntegerField("Current Hit Points", validators=[DataRequired(), Length(min=2, max=20)])
    hp_temp = IntegerField("Temporary Hit Points", validators=[DataRequired(), Length(min=2, max=20)])
    hd_total = StringField("Total", validators=[DataRequired(), Length(min=2, max=20)])
    hd_current = StringField("Hit Dice", validators=[DataRequired(), Length(min=2, max=20)])
    ds_success1 = BooleanField("ds_success1")
    ds_success2 = BooleanField("ds_success2")
    ds_success3 = BooleanField("ds_success3")
    ds_failure1 = BooleanField("ds_failure1")
    ds_failure2 = BooleanField("ds_failure2")
    ds_failure3 = BooleanField("ds_failure3")
    cp = IntegerField("CP", validators=[DataRequired(), Length(min=2, max=20)])
    sp = IntegerField("SP", validators=[DataRequired(), Length(min=2, max=20)])
    ep = IntegerField("EP", validators=[DataRequired(), Length(min=2, max=20)])
    gp = IntegerField("GP", validators=[DataRequired(), Length(min=2, max=20)])
    pp = IntegerField("PP", validators=[DataRequired(), Length(min=2, max=20)])
    equipment = TextAreaField("Equipment", validators=[DataRequired()])
    personality  = TextAreaField("Personality", validators=[DataRequired()])
    ideals = TextAreaField("Ideals", validators=[DataRequired()])
    bonds = TextAreaField("Bonds", validators=[DataRequired()])
    flaws = TextAreaField("Flaws", validators=[DataRequired()])
    features_traits = TextAreaField("Features & Traits", validators=[DataRequired()])
    other_prof_lang = TextAreaField("Other Proficiencies and Languages", validators=[DataRequired()])
    submit = SubmitField("Save")

sae/characters/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from sae import db
from sae.models import Character
from sae.characters.forms import CharacterForm

characters = Blueprint("characters", __name__)

@characters.route("/character/new")
@login_required
def new_character():
    user = current_user
    form = CharacterForm()
    if form.validate_on_submit():
        #filling the table with values
        character = Character(character_name=form.character_name,
                            character_class=form.character_class,
                            level=form.level,
                            background=form.background,
                            player_name=form.player_name,
                            race=form.race,
                            alignment=form.alignment,
                            exp=form.exp,
                            strength=form.strength,
                            dexterity=form.dexterity,
                            constitution=form.constitution,
                            wisdom=form.wisdom,
                            intelligence=form.intelligence,
                            charisma=form.charisma,
                            inspiration=form.inspiration,
                            prof=form.prof,
                            st_str=form.st_str,
                            st_dex=form.st_dex,
                            st_con=form.st_con,
                            st_wis=form.st_wis,
                            st_int=form.st_int,
                            st_cha=form.st_cha,
                            acrobatics=form.acrobatics,
                            animal_handling=form.animal_handling,
                            arcana=form.arcana,
                            athletics=form.athletics,
                            deception=form.deception,
                            history=form.history,
                            insight=form.insight,
                            intimidation=form.intimidation,
                            investigation=form.investigation,
                            medicine=form.medicine,
                            nature=form.nature,
                            perception=form.perception,
                            performance=form.performance,
                            persuation=form.persuation,
                            religion=form.religion,
                            sleight_of_hand=form.sleight_of_hand,
                            stealth=form.stealth,
                            survival=form.survival,
                            armor_class=form.armor_class,
                            initiative=form.initiative,
                            speed=form.speed,
                            hp_max=form.hp_max,
                            hp_current=form.hp_current,
                            hp_temp=form.hp_temp,
                            hd_total=form.hd_total,
                            hd_current=form.hd_current,
                            ds_success1=form.ds_success1,
                            ds_success2=form.ds_success2,
                            ds_success3=form.ds_success3,
                            ds_failure1=form.ds_failure1,
                            ds_failure2=form.ds_failure2,
                            ds_failure3=form.ds_failure3,
                            cp=form.cp,
                            sp=form.sp,
                            ep=form.ep,
                            gp=form.gp,
                            pp=form.pp,
                            equipment=form.equipment,
                            personality=form.personality,
                            ideals=form.ideals,
                            bonds=form.bonds,
                            flaws=form.flaws,
                            features_traits=form.features_traits,
                            other_prof_lang=form.other_prof_lang,
                            user_id=user.id
                            )
        #adding the table to the db                                                                                                                                                                                  Ich hasse mein Leben
        db.session.add(character)
        db.session.commit()
        flash("The Character has been created!", "success")
        return redirect(url_for("main.home"))
    return render_template("character_sheet.html", form=form)


@characters.route("/character/<int:character_id>")
@login_required
def character_sheet(character_id):
    user = current_user
    character = Character.query.filter_by(id=character_id).first_or_404()
    if character.author.id is not user.id:
        flash("You do not have access to this Character", "danger")
        return redirect(url_for("main.home"))
    return redirect(url_for(characters))
    form = Characterform()

sae/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from sae import db, bcrypt
from sae.users.forms import RegistrationForm, LoginForm
from sae.models import User

users = Blueprint("users", __name__)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in!", "danger")
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("main.home")) 
        else:
            flash("Login unsuccessful. Please check email and password!", "danger")
    return render_template("login.html", title="Login", form=form)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in!", "danger")
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))

sae/templates/characters.html
{% extends "layout.html" %}
{% block content %}
  <h1 class="mb-3">Characters by {{ user.username }} ({{ characters.total }}) </h1>
  {% for character in characters.items %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <small class="mr-2">{{ character.author.username }}</small>
        <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
      </div>
      <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ character.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4"href="{{ url_for('users.user_posts', username=user.username,  page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4"href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

sae/templates/home.html
{% extends "layout.html" %}
{% block content %}
    test
  <h1 class="mb-3">Characters by {{ user.username }} ({{ characters.total }}) </h1>
  {% for character in characters.items %}
  <article class="media content-section">
    <div class="media-body">
      <h2><a class="article-title" href="{{ url_for('main.character', character_id=character.id) }}">{{ character.character_name }}</a></h2>
    </div>
  </article>
  {% endfor %}
{% endblock content %}

sae/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{{url_for("static", filename="bootstrap.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="main.css") }}">
    {% if title %}
      <title>Character Sheet - {{ title }}</title>
    {% else %}
      <title>Character Sheet</title>
    {% endif %}
  </head>
  <body>
    <main role="main" class="container">
      <div class="row">
        <div class="col-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{{ url_for("static", filename="sheet.js") }}" ></script>
  </body>
</html>

sae/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Login</legend>
          <div class"form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class"form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-check">
            {{ form.remember(class="form-check-input") }}
            {{ form.remember.label(class="form-check-label") }}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
    </div>
    <div class="border-top pt-3">
      <small class="tex-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
      </small>
    </div>
{% endblock content %}

sae/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Join Today</legend>
          <div class"form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class"form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class"form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class"form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors %}
              {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.confirm_password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
    </div>
    <div class="border-top pt-3">
      <small class="tex-muted">
        Already Have An Account <a class="ml-2" href="{{ url_for("users.login") }}">Sign In</a>
      </small>
    </div>
{% endblock content %}